apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cron
spec:
  schedule: "*/5 * * * *"   # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: alpine:3.20
            workingDir: /work
            command:
              - sh
              - -c
              - |
                apk add --no-cache bash curl jq
                bash /scripts/api_health_check.sh # jis cript ko cronjob se chalana hai 
            env:
            - name: MOBILE
              valueFrom:
                secretKeyRef:
                  name: health-check-secrets
                  key: MOBILE
            - name: OTP
              valueFrom:
                secretKeyRef:
                  name: health-check-secrets
                  key: OTP
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: health-check-secrets
                  key: SLACK_WEBHOOK_URL
            - name: PAGERDUTY_INTEGRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: health-check-secrets
                  key: PAGERDUTY_INTEGRATION_KEY
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: pages-volume
              mountPath: /pages
            - name: workdir
              mountPath: /work
          restartPolicy: OnFailure
          volumes:
          - name: script-volume
            configMap:
              name: health-check-script
          - name: pages-volume
            configMap:
              name: health-check-pages
          - name: workdir
            emptyDir: {}

