# health-check-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: health-check-secrets
type: Opaque
stringData:
  MOBILE: "$MOBILEE" #jo bhi default no hai(mendatory to filled)
  OTP: "$OTPP" # jo bhi default otp hai(mendatory to filled)
  SLACK_WEBHOOK_URL: "$SLACK_WEBHOOK_URLL" #(mendatory to filled) webhook url jisame hamako handaled wali api ka data bhejan hai 
  PAGERDUTY_INTEGRATION_KEY: "$INTEGRATION_KEY" #(mendatory to filled) pagerduty api intgration key
